-- Migration: Seed All Location Factors
DO $$
DECLARE
  ws_id UUID;
BEGIN
  -- Get the first workspace ID
  SELECT id INTO ws_id FROM workspaces LIMIT 1;

  IF ws_id IS NOT NULL THEN
    -- Optional: Delete existing factors if you want to reset
    -- DELETE FROM location_factors WHERE workspace_id = ws_id;

    INSERT INTO location_factors (workspace_id, province, city, regional_factor, difficulty_factor) VALUES
    (ws_id, 'DKI Jakarta', NULL, 0.97, 1.05),
    (ws_id, 'DKI Jakarta', 'Jakarta Pusat', 1, 1),
    (ws_id, 'DKI Jakarta', 'Jakarta Selatan', 0.99, 1),
    (ws_id, 'DKI Jakarta', 'Jakarta Barat', 0.98, 1),
    (ws_id, 'DKI Jakarta', 'Jakarta Utara', 0.97, 1),
    (ws_id, 'DKI Jakarta', 'Jakarta Timur', 0.96, 1),
    (ws_id, 'DKI Jakarta', 'Kepulauan Seribu', 0.95, 1.15),
    (ws_id, 'Banten', NULL, 0.9, 1.05),
    (ws_id, 'Banten', 'Tangerang Kota', 0.95, 1),
    (ws_id, 'Banten', 'Tangerang Selatan', 0.96, 1.05),
    (ws_id, 'Banten', 'Tangerang Kab', 0.94, 1),
    (ws_id, 'Banten', 'Serang Kota', 0.9, 1.05),
    (ws_id, 'Banten', 'Serang Kab', 0.89, 1.05),
    (ws_id, 'Banten', 'Lebak', 0.85, 1.1),
    (ws_id, 'Banten', 'Cilegon', 0.92, 1.05),
    (ws_id, 'Banten', 'Pandeglang', 0.86, 1.1),
    (ws_id, 'Banten', 'BSD/Alam Sutera', 0.97, 1.05),
    (ws_id, 'Banten', 'Karawaci/Lippo', 0.96, 1.05),
    (ws_id, 'Banten', 'Industri Merak', 0.93, 1),
    (ws_id, 'Banten', 'Wisata Pantai Pandeglang', 0.87, 1.1),
    (ws_id, 'Banten', 'Lebak Selatan', 0.83, 1.2),
    (ws_id, 'Jawa Barat', NULL, 0.88, 1.1),
    (ws_id, 'Jawa Barat', 'Bekasi Kota', 0.95, 1),
    (ws_id, 'Jawa Barat', 'Bekasi Kab', 0.94, 1),
    (ws_id, 'Jawa Barat', 'Depok', 0.95, 1),
    (ws_id, 'Jawa Barat', 'Bogor Kota', 0.94, 1),
    (ws_id, 'Jawa Barat', 'Bogor Kab', 0.92, 1.05),
    (ws_id, 'Jawa Barat', 'Bandung Kota', 0.92, 1.05),
    (ws_id, 'Jawa Barat', 'Bandung Kab', 0.9, 1.05),
    (ws_id, 'Jawa Barat', 'Bandung Barat', 0.89, 1.05),
    (ws_id, 'Jawa Barat', 'Cimahi', 0.91, 1.05),
    (ws_id, 'Jawa Barat', 'Sukabumi Kota', 0.9, 1.05),
    (ws_id, 'Jawa Barat', 'Sukabumi Kab', 0.87, 1.1),
    (ws_id, 'Jawa Barat', 'Cirebon Kota', 0.89, 1.05),
    (ws_id, 'Jawa Barat', 'Cirebon Kab', 0.88, 1.1),
    (ws_id, 'Jawa Barat', 'Tasikmalaya Kota', 0.88, 1.1),
    (ws_id, 'Jawa Barat', 'Tasikmalaya Kab', 0.86, 1.1),
    (ws_id, 'Jawa Barat', 'Banjar Kota', 0.86, 1.1),
    (ws_id, 'Jawa Barat', 'Cianjur', 0.88, 1.1),
    (ws_id, 'Jawa Barat', 'Indramayu', 0.87, 1.1),
    (ws_id, 'Jawa Barat', 'Sumedang', 0.88, 1.1),
    (ws_id, 'Jawa Barat', 'Subang', 0.88, 1.1),
    (ws_id, 'Jawa Barat', 'Karawang', 0.9, 1.05),
    (ws_id, 'Jawa Barat', 'Purwakarta', 0.89, 1.05),
    (ws_id, 'Jawa Barat', 'Kuningan', 0.87, 1.1),
    (ws_id, 'Jawa Barat', 'Garut', 0.86, 1.1),
    (ws_id, 'Jawa Barat', 'Pangandaran', 0.87, 1.1),
    (ws_id, 'Jawa Tengah', NULL, 0.85, 1.1),
    (ws_id, 'Jawa Tengah', 'Semarang Kota', 0.88, 1.1),
    (ws_id, 'Jawa Tengah', 'Semarang Kab', 0.87, 1.1),
    (ws_id, 'Jawa Tengah', 'Surakarta Kota', 0.87, 1.1),
    (ws_id, 'Jawa Tengah', 'Salatiga Kota', 0.86, 1.1),
    (ws_id, 'Jawa Tengah', 'Banyumas', 0.85, 1.1),
    (ws_id, 'Jawa Tengah', 'Purworejo', 0.84, 1.2),
    (ws_id, 'Jawa Tengah', 'Magelang Kota', 0.85, 1.1),
    (ws_id, 'Jawa Tengah', 'Magelang Kab', 0.85, 1.1),
    (ws_id, 'Jawa Tengah', 'Pekalongan Kota', 0.85, 1.1),
    (ws_id, 'Jawa Tengah', 'Pekalongan Kab', 0.85, 1.1),
    (ws_id, 'Jawa Tengah', 'Tegal Kota', 0.84, 1.2),
    (ws_id, 'Jawa Tengah', 'Tegal Kab', 0.84, 1.2),
    (ws_id, 'Jawa Tengah', 'Boyolali', 0.86, 1.1),
    (ws_id, 'Jawa Tengah', 'Sukoharjo', 0.86, 1.1),
    (ws_id, 'Jawa Tengah', 'Karanganyar', 0.86, 1.1),
    (ws_id, 'Jawa Tengah', 'Klaten', 0.85, 1.1),
    (ws_id, 'Jawa Tengah', 'Sragen', 0.84, 1.2),
    (ws_id, 'Jawa Tengah', 'Wonogiri', 0.83, 1.2),
    (ws_id, 'Jawa Tengah', 'Kebumen', 0.84, 1.2),
    (ws_id, 'Jawa Tengah', 'Wonosobo', 0.83, 1.2),
    (ws_id, 'Jawa Tengah', 'Temanggung', 0.83, 1.2),
    (ws_id, 'Jawa Tengah', 'Banjarnegara', 0.83, 1.2),
    (ws_id, 'Jawa Tengah', 'Purbalingga', 0.84, 1.2),
    (ws_id, 'Jawa Tengah', 'Cilacap', 0.84, 1.2),
    (ws_id, 'Jawa Tengah', 'Brebes', 0.83, 1.2),
    (ws_id, 'Jawa Tengah', 'Pemalang', 0.84, 1.2),
    (ws_id, 'Jawa Tengah', 'Batang', 0.85, 1.1),
    (ws_id, 'Jawa Tengah', 'Kendal', 0.86, 1.1),
    (ws_id, 'Jawa Tengah', 'Demak', 0.86, 1.1),
    (ws_id, 'Jawa Tengah', 'Kudus', 0.86, 1.1),
    (ws_id, 'Jawa Tengah', 'Jepara', 0.85, 1.1),
    (ws_id, 'Jawa Tengah', 'Pati', 0.85, 1.1),
    (ws_id, 'Jawa Tengah', 'Rembang', 0.84, 1.2),
    (ws_id, 'Jawa Tengah', 'Blora', 0.83, 1.2),
    (ws_id, 'DI Yogyakarta', NULL, 0.86, 1.1),
    (ws_id, 'DI Yogyakarta', 'Yogyakarta Kota', 0.87, 1.1),
    (ws_id, 'DI Yogyakarta', 'Sleman', 0.86, 1.1),
    (ws_id, 'DI Yogyakarta', 'Bantul', 0.85, 1.1),
    (ws_id, 'DI Yogyakarta', 'Kulon Progo', 0.84, 1.2),
    (ws_id, 'DI Yogyakarta', 'Gunungkidul', 0.83, 1.2),
    (ws_id, 'Jawa Timur', NULL, 0.87, 1.1),
    (ws_id, 'Jawa Timur', 'Surabaya', 0.9, 1.05),
    (ws_id, 'Jawa Timur', 'Malang Kota', 0.88, 1.1),
    (ws_id, 'Jawa Timur', 'Malang Kab', 0.87, 1.1),
    (ws_id, 'Jawa Timur', 'Madiun Kota', 0.85, 1.1),
    (ws_id, 'Jawa Timur', 'Madiun Kab', 0.84, 1.2),
    (ws_id, 'Jawa Timur', 'Batu Kota', 0.88, 1.1),
    (ws_id, 'Jawa Timur', 'Mojokerto Kota', 0.87, 1.1),
    (ws_id, 'Jawa Timur', 'Mojokerto Kab', 0.88, 1.1),
    (ws_id, 'Jawa Timur', 'Pasuruan Kota', 0.86, 1.1),
    (ws_id, 'Jawa Timur', 'Pasuruan Kab', 0.87, 1.1),
    (ws_id, 'Jawa Timur', 'Probolinggo Kota', 0.85, 1.1),
    (ws_id, 'Jawa Timur', 'Probolinggo Kab', 0.84, 1.2),
    (ws_id, 'Jawa Timur', 'Kediri Kota', 0.86, 1.1),
    (ws_id, 'Jawa Timur', 'Kediri Kab', 0.86, 1.1),
    (ws_id, 'Jawa Timur', 'Blitar Kota', 0.85, 1.1),
    (ws_id, 'Jawa Timur', 'Blitar Kab', 0.85, 1.1),
    (ws_id, 'Jawa Timur', 'Sidoarjo', 0.89, 1.05),
    (ws_id, 'Jawa Timur', 'Gresik', 0.89, 1.05),
    (ws_id, 'Jawa Timur', 'Jombang', 0.86, 1.1),
    (ws_id, 'Jawa Timur', 'Nganjuk', 0.85, 1.1),
    (ws_id, 'Jawa Timur', 'Tulungagung', 0.85, 1.1),
    (ws_id, 'Jawa Timur', 'Lamongan', 0.86, 1.1),
    (ws_id, 'Jawa Timur', 'Bojonegoro', 0.85, 1.1),
    (ws_id, 'Jawa Timur', 'Tuban', 0.86, 1.1),
    (ws_id, 'Jawa Timur', 'Magetan', 0.84, 1.2),
    (ws_id, 'Jawa Timur', 'Ngawi', 0.84, 1.2),
    (ws_id, 'Jawa Timur', 'Ponorogo', 0.83, 1.2),
    (ws_id, 'Jawa Timur', 'Pacitan', 0.82, 1.2),
    (ws_id, 'Jawa Timur', 'Lumajang', 0.84, 1.2),
    (ws_id, 'Jawa Timur', 'Jember', 0.85, 1.1),
    (ws_id, 'Jawa Timur', 'Bondowoso', 0.83, 1.2),
    (ws_id, 'Jawa Timur', 'Situbondo', 0.84, 1.2),
    (ws_id, 'Jawa Timur', 'Banyuwangi', 0.86, 1.1),
    (ws_id, 'Jawa Timur', 'Bangkalan', 0.83, 1.2),
    (ws_id, 'Jawa Timur', 'Sampang', 0.82, 1.2),
    (ws_id, 'Jawa Timur', 'Pamekasan', 0.83, 1.2),
    (ws_id, 'Jawa Timur', 'Sumenep', 0.82, 1.2),
    (ws_id, 'Bali', NULL, 0.92, 1.05),
    (ws_id, 'Bali', 'Denpasar', 0.93, 1),
    (ws_id, 'Bali', 'Badung', 0.95, 1),
    (ws_id, 'Bali', 'Gianyar', 0.94, 1),
    (ws_id, 'Bali', 'Tabanan', 0.92, 1.05),
    (ws_id, 'Bali', 'Bangli', 0.91, 1.05),
    (ws_id, 'Bali', 'Buleleng', 0.9, 1.05),
    (ws_id, 'Bali', 'Karangasem', 0.89, 1.05),
    (ws_id, 'Bali', 'Klungkung', 0.9, 1.05),
    (ws_id, 'Bali', 'Jembrana', 0.89, 1.05),
    (ws_id, 'NTB', NULL, 0.88, 1.1),
    (ws_id, 'NTB', 'Mataram', 0.89, 1.05),
    (ws_id, 'NTB', 'Lombok', 0.88, 1.1),
    (ws_id, 'NTT', NULL, 0.82, 1.2),
    (ws_id, 'NTT', 'Kupang', 0.83, 1.2),
    (ws_id, 'Aceh', NULL, 0.84, 1.2),
    (ws_id, 'Aceh', 'Banda Aceh', 0.85, 1.1),
    (ws_id, 'Sumatera Utara', NULL, 0.88, 1.1),
    (ws_id, 'Sumatera Utara', 'Medan', 0.9, 1.05),
    (ws_id, 'Sumatera Barat', NULL, 0.86, 1.1),
    (ws_id, 'Sumatera Barat', 'Padang', 0.87, 1.1),
    (ws_id, 'Riau', NULL, 0.89, 1.05),
    (ws_id, 'Riau', 'Pekanbaru', 0.9, 1.05),
    (ws_id, 'Kep. Riau', NULL, 0.9, 1.05),
    (ws_id, 'Kep. Riau', 'Tanjung Pinang', 0.89, 1.05),
    (ws_id, 'Kep. Riau', 'Batam', 0.92, 1.05),
    (ws_id, 'Jambi', NULL, 0.85, 1.1),
    (ws_id, 'Jambi', 'Jambi', 0.86, 1.1),
    (ws_id, 'Sumatera Selatan', NULL, 0.87, 1.1),
    (ws_id, 'Sumatera Selatan', 'Palembang', 0.88, 1.1),
    (ws_id, 'Bengkulu', NULL, 0.84, 1.2),
    (ws_id, 'Bengkulu', 'Bengkulu', 0.85, 1.1),
    (ws_id, 'Kep. Bangka Belitung', NULL, 0.86, 1.1),
    (ws_id, 'Kep. Bangka Belitung', 'Pangkalpinang', 0.87, 1.1),
    (ws_id, 'Lampung', NULL, 0.85, 1.1),
    (ws_id, 'Lampung', 'Bandar Lampung', 0.86, 1.1),
    (ws_id, 'Lampung', 'Lampung Barat', 0.82, 1.2),
    (ws_id, 'Kalimantan Barat', NULL, 0.88, 1.1),
    (ws_id, 'Kalimantan Barat', 'Pontianak', 0.89, 1.05),
    (ws_id, 'Kalimantan Barat', 'Singkawang', 0.9, 1.05),
    (ws_id, 'Kalimantan Tengah', NULL, 0.87, 1.1),
    (ws_id, 'Kalimantan Tengah', 'Palangka Raya', 0.88, 1.1),
    (ws_id, 'Kalimantan Selatan', NULL, 0.88, 1.1),
    (ws_id, 'Kalimantan Selatan', 'Banjarmasin', 0.89, 1.05),
    (ws_id, 'Kalimantan Selatan', 'Banjarbaru', 0.89, 1.05),
    (ws_id, 'Kalimantan Timur', NULL, 0.9, 1.05),
    (ws_id, 'Kalimantan Timur', 'Samarinda', 0.91, 1.05),
    (ws_id, 'Kalimantan Timur', 'Balikpapan', 0.93, 1),
    (ws_id, 'Kalimantan Timur', 'IKN', 0.95, 1.25),
    (ws_id, 'Kalimantan Utara', NULL, 0.89, 1.05),
    (ws_id, 'Kalimantan Utara', 'Tanjung Selor', 0.9, 1.05),
    (ws_id, 'Kalimantan Utara', 'Tarakan', 0.91, 1.05),
    (ws_id, 'Sulawesi Utara', NULL, 0.9, 1.05),
    (ws_id, 'Sulawesi Utara', 'Manado', 0.91, 1.05),
    (ws_id, 'Sulawesi Utara', 'Bitung', 0.92, 1.05),
    (ws_id, 'Gorontalo', NULL, 0.86, 1.1),
    (ws_id, 'Gorontalo', 'Gorontalo', 0.87, 1.1),
    (ws_id, 'Sulawesi Tengah', NULL, 0.87, 1.1),
    (ws_id, 'Sulawesi Tengah', 'Palu', 0.88, 1.1),
    (ws_id, 'Sulawesi Tengah', 'Luwuk', 0.89, 1.05),
    (ws_id, 'Sulawesi Barat', NULL, 0.85, 1.1),
    (ws_id, 'Sulawesi Barat', 'Mamuju', 0.86, 1.1),
    (ws_id, 'Sulawesi Selatan', NULL, 0.89, 1.05),
    (ws_id, 'Sulawesi Selatan', 'Makassar', 0.91, 1.05),
    (ws_id, 'Sulawesi Selatan', 'Parepare', 0.9, 1.05),
    (ws_id, 'Sulawesi Selatan', 'Palopo', 0.89, 1.05),
    (ws_id, 'Sulawesi Tenggara', NULL, 0.86, 1.1),
    (ws_id, 'Sulawesi Tenggara', 'Kendari', 0.87, 1.1),
    (ws_id, 'Sulawesi Tenggara', 'Baubau', 0.88, 1.1),
    (ws_id, 'Maluku', NULL, 0.83, 1.2),
    (ws_id, 'Maluku', 'Ambon', 0.84, 1.2),
    (ws_id, 'Maluku Utara', NULL, 0.84, 1.2),
    (ws_id, 'Maluku Utara', 'Sofifi', 0.83, 1.2),
    (ws_id, 'Maluku Utara', 'Ternate', 0.86, 1.2),
    (ws_id, 'Papua', NULL, 0.8, 1.2),
    (ws_id, 'Papua', 'Jayapura', 0.82, 1.25),
    (ws_id, 'Papua Barat', NULL, 0.81, 1.2),
    (ws_id, 'Papua Barat', 'Manokwari', 0.82, 1.2),
    (ws_id, 'Papua Barat Daya', NULL, 0.82, 1.2),
    (ws_id, 'Papua Barat Daya', 'Sorong', 0.85, 1.25),
    (ws_id, 'Papua Tengah', NULL, 0.78, 1.35),
    (ws_id, 'Papua Tengah', 'Nabire', 0.8, 1.2),
    (ws_id, 'Papua Pegunungan', NULL, 0.76, 1.35),
    (ws_id, 'Papua Pegunungan', 'Wamena', 0.78, 1.4),
    (ws_id, 'Papua Selatan', NULL, 0.79, 1.35),
    (ws_id, 'Papua Selatan', 'Merauke', 0.81, 1.2)
    ON CONFLICT (workspace_id, province, city) DO UPDATE SET
    regional_factor = EXCLUDED.regional_factor,
    difficulty_factor = EXCLUDED.difficulty_factor;
  END IF;
END $$;
